import { TECH_DOCS } from "./techdocs";

export type LessonAction = {
  title: string;
  instruction: string;
  note?: string;
};

export type Lesson = {
  id: string;
  title: string;
  objective: string;
  duration: string;
  path: string[];
  before: string[];
  actions: LessonAction[];
  success: string[];
  troubleshooting: { problem: string; fix: string }[];
  docUrl: string;
  architecture?: string[];
  commonMistake?: string;
  image?: string;
  imageAlt?: string;
  videoId?: string;
  videoTitle?: string;
};

const images = {
  botPicker: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/VAIG_Cloud/Connect%20your%20bot_latest_2.png",
  agentFramework: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-LiveHubAIAgentFramework.png",
  speechSettings: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/VAIG_Cloud/byoc_botsett_data_msftVGA.png",
  routeCreate: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/livehub-create-new-routing-rule.png",
  routeList: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LiveHubExpandRoutingRule.png",
  testCard: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/Test-your-bot-card.png",
  testDialog: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-%20Bot-testing.png",
  callHistory: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-callhistory-new.png",
  callSummary: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-call-summary.png",
  botLatency: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/BotLatency.png",
  sipLadder: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/VAIG_Cloud/LH-call-history-sip-ladder.png",
  teamsCreate: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/VAIG_Cloud/Teams-Create_Conn.png",
  whatsappCreate: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-whatsapp-addnew.png",
  assistPicker: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/Connect%20your%20assist-bot.png",
  assistOutside: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LHAgentAssitDiagram-outsideLiveHub.png",
  assistRoute: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LiveHub_AgentAssit_routing.png",
  translationGeneral: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-voice-translation-configure-general.png",
  translationLanguages: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-voice-translation-languages.png",
  translationAdvanced: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-voice-translation-configure-advanced.png",
  translationDynamic: "https://techdocs.audiocodes.com/livehub/Content/Resources/Images/LiveHub/LH-voice-translation-languages-dynamic.png",
};

export const lessonsByTrack: Record<string, Lesson[]> = {
  "voice-agent": [
    {
      id: "create-agent",
      title: "Create a focused AI agent",
      objective: "Finish with one saved agent whose job and opening behavior are easy to test.",
      duration: "5 min",
      path: ["AI Agents", "Agents", "Add new agent"],
      architecture: ["Caller", "Voice channel", "Routing rule", "Bot connection", "AI agent"],
      before: ["A clear agent name", "One job the agent should do", "One question a caller will ask"],
      actions: [
        { title: "Open the agent builder", instruction: "From the left menu, open AI Agents → Agents, then select Add new agent." },
        { title: "Name the outcome", instruction: "Use a name that explains the job and environment, such as Support-Triage-QA." },
        { title: "Write one clear job", instruction: "Describe one outcome: “Answer basic support questions and collect the caller’s case number.”" },
        { title: "Choose how the conversation starts", instruction: "Add a short greeting or opening behavior so you can recognize the agent during a test." },
        { title: "Save and reopen", instruction: "Save the agent, return to the list, and reopen it to prove the configuration persisted." },
      ],
      success: ["The agent appears in the Agents list", "You can reopen it without an error", "Its name and purpose are easy to recognize"],
      troubleshooting: [
        { problem: "The agent is missing", fix: "Confirm the Current account at the top of Live Hub, then return to AI Agents → Agents and save again." },
        { problem: "The scope feels vague", fix: "Use one audience, one task, and one expected result. Expand only after the smallest version works." },
      ],
      commonMistake: "Building a do-everything agent before proving one small conversation.",
      docUrl: TECH_DOCS.aiAgent,
      image: images.agentFramework,
      imageAlt: "Live Hub AI Agent framework selection screen",
      videoId: "Ggv2W6vYtIo",
      videoTitle: "Quick Start Guide for Voice AI Live Hub Setup",
    },
    {
      id: "prompt-and-chat",
      title: "Prompt it and prove the chat",
      objective: "Make the agent reliable in text before adding speech or telephony variables.",
      duration: "7 min",
      path: ["AI Agents", "Agents", "Edit agent", "Instructions and chat test"],
      architecture: ["Test message", "Agent instructions", "Model response", "Expected outcome"],
      before: ["The saved agent", "Three realistic caller questions", "One request the agent should refuse or escalate"],
      actions: [
        { title: "Set identity and objective", instruction: "Tell the agent who it is, who it helps, and the result it must achieve." },
        { title: "Add operating rules", instruction: "State what information to collect, what it may not invent, and when it should hand off or stop." },
        { title: "Write for voice", instruction: "Use short sentences, spoken-friendly wording, and one question at a time—even in the chat test." },
        { title: "Run three scenarios", instruction: "Test one normal request, one unclear request, and one unsupported request. Keep the wording you will reuse later by voice." },
        { title: "Change one thing", instruction: "If a result is weak, change only one instruction and repeat the same scenario so you know what helped." },
      ],
      success: ["The normal request is handled correctly", "The agent asks for clarification instead of guessing", "The unsupported request is refused or escalated as designed"],
      troubleshooting: [
        { problem: "Answers vary too much", fix: "Make the expected outcome and forbidden behavior explicit, then repeat the exact same test message." },
        { problem: "The answer is correct but too long", fix: "Add a spoken-response rule such as “answer in two short sentences, then ask one question.”" },
      ],
      commonMistake: "Debugging voice quality before proving that the agent logic works in chat.",
      docUrl: TECH_DOCS.aiAgent,
    },
    {
      id: "enable-voice",
      title: "Enable speech and telephony",
      objective: "Turn the working agent into a callable voice endpoint using the current Live Hub workflow.",
      duration: "6 min",
      path: ["AI Agents", "Agents", "Edit agent", "Speech and Telephony"],
      architecture: ["Caller audio", "STT or voice streaming", "AI agent", "TTS or voice streaming"],
      before: ["The caller’s main language", "A preferred voice", "The Live Hub region used by your channel"],
      actions: [
        { title: "Open Speech and Telephony", instruction: "Edit the agent, open Speech and Telephony, and enable voice." },
        { title: "Choose the audio path", instruction: "For a standard model, configure STT and TTS. Use voice streaming only with a compatible real-time audio model.", note: "When voice streaming is enabled, separate STT and TTS fields may disappear." },
        { title: "Choose speech settings", instruction: "Select provider, model, language, and a TTS voice that supports the same locale." },
        { title: "Set conversation controls", instruction: "Review barge-in, DTMF, maximum duration, and any recording or transcript choices needed for the test." },
        { title: "Save and check Bot connections", instruction: "Save the agent. In current releases, Live Hub creates the associated Bot connection automatically. If your older release shows a manual connection wizard, select LiveHub AI Agent there and choose this agent." },
      ],
      success: ["Speech and Telephony is enabled", "The associated Bot connection exists", "STT/TTS language and region match the planned call path"],
      troubleshooting: [
        { problem: "STT and TTS fields disappeared", fix: "Voice streaming is enabled. Turn it off to use separate speech services." },
        { problem: "No Bot connection appears", fix: "Save the agent, refresh Bot connections, and confirm you are in the same Current account. On older releases, create the connection manually." },
        { problem: "The voice sounds wrong", fix: "Confirm the TTS voice locale matches the configured language." },
      ],
      commonMistake: "Creating a second manual Bot connection when the agent already generated one automatically.",
      docUrl: TECH_DOCS.aiAgent,
      image: images.speechSettings,
      imageAlt: "Speech-to-text and text-to-speech settings in Live Hub",
    },
    {
      id: "voice-test",
      title: "Make a browser test call",
      objective: "Prove the complete agent-and-speech experience before adding phone numbers or routing.",
      duration: "5 min",
      path: ["Bot connections", "Your AI agent connection", "Phone icon"],
      architecture: ["Browser microphone", "Bot connection", "Speech", "AI agent", "Browser speaker"],
      before: ["The generated Bot connection", "Browser microphone permission", "The three scenarios from the chat test"],
      actions: [
        { title: "Open Test Call", instruction: "Find the Bot connection created for the agent and select its phone icon." },
        { title: "Check devices", instruction: "Open test settings and confirm the correct microphone and speaker. Allow browser access if prompted." },
        { title: "Call the agent", instruction: "Select Call your bot, wait for the greeting, and say the same normal request you used in chat." },
        { title: "Test turn-taking", instruction: "Interrupt one long response to verify barge-in, and press a digit if your design uses DTMF." },
        { title: "Record the result", instruction: "Write down what the agent heard, what it said, and whether the call ended normally." },
      ],
      success: ["You hear the greeting", "The agent understands the test sentence", "Barge-in or DTMF behaves as intended", "The call ends normally"],
      troubleshooting: [
        { problem: "You hear nothing", fix: "Check browser microphone and speaker permissions before editing Live Hub." },
        { problem: "The agent answers but cannot understand", fix: "Inspect the recognized transcript and STT language/model. This is an audio or speech issue, not a prompt issue." },
      ],
      commonMistake: "Building a routing rule before the agent passes a direct browser voice test.",
      docUrl: TECH_DOCS.botTest,
      image: images.testCard,
      imageAlt: "Live Hub Bot connection card with the test-call control",
    },
    {
      id: "connect-number",
      title: "Add a first phone number",
      objective: "Create one simple public entry point for the first real call.",
      duration: "5 min",
      path: ["Voice channels", "Phone numbers", "Add"],
      architecture: ["Caller", "Live Hub number", "Routing rule", "Bot connection"],
      before: ["Target country", "Expected call volume", "The same region as the Bot connection"],
      actions: [
        { title: "Open Phone numbers", instruction: "From Voice channels, open Phone numbers and start the Add or purchase wizard." },
        { title: "Choose country and number", instruction: "Select the required country and an available DID." },
        { title: "Review limits and region", instruction: "Keep the region aligned with the Bot connection and confirm the account can support the expected test traffic." },
        { title: "Complete the purchase", instruction: "Finish the wizard and wait until the number is available." },
        { title: "Leave it unassigned", instruction: "Do not look for an agent assignment on the number. The routing rule in the next lesson makes that connection." },
      ],
      success: ["The number appears under Phone numbers", "Its region matches the Bot connection", "It is ready to use as a Call origin"],
      troubleshooting: [
        { problem: "No number is available", fix: "Try the required number type or country again, and check account plan or balance restrictions." },
        { problem: "The number says unassigned", fix: "That is expected until a routing rule uses it as the origin." },
      ],
      commonMistake: "Trying to assign a number directly to an AI agent instead of connecting them with a routing rule.",
      docUrl: TECH_DOCS.phoneNumbers,
    },
    {
      id: "route-call-observe",
      title: "Route, call, and inspect both histories",
      objective: "Complete a real phone call and prove both the telephony path and AI behavior.",
      duration: "6 min",
      path: ["Routing", "Routing Rules", "Add new routing rule"],
      architecture: ["Phone number", "Routing rule", "Bot connection", "AI agent", "Calls + AI Logs"],
      before: ["The ready phone number", "The ready Bot connection", "A second phone to place the test call"],
      actions: [
        { title: "Create the rule", instruction: "Set Type to Call, select the Live Hub number as Call origin, and select the generated Bot connection under Route To." },
        { title: "Keep the first match exact", instruction: "Use the exact called number for the first test. Broaden or add patterns only after this route works." },
        { title: "Place a real call", instruction: "Call the number, complete the same scenario used in chat and browser voice testing, then hang up normally." },
        { title: "Inspect Calls", instruction: "Open Calls and review completion status, routing, services, duration, transcript, audio, latency, and SIP ladder when available." },
        { title: "Inspect AI Agents Logs", instruction: "Use AI Agents logs to review prompts, responses, tools, variables, and post-call analysis. Calls proves telephony; AI Logs explains the agent." },
      ],
      success: ["The phone call reaches the correct agent", "A record appears in Calls", "A matching AI log exists", "You can explain the result using evidence from both views"],
      troubleshooting: [
        { problem: "The call never appears in Calls", fix: "The failure happened before Live Hub. Check the dialed number, carrier, or source channel." },
        { problem: "The call appears but does not reach the agent", fix: "Check routing, region, called-number format, rule order, and destination Bot connection." },
        { problem: "The agent understands but answers badly", fix: "The voice path works. Use AI Logs to inspect instructions, documents, tools, variables, and model behavior." },
      ],
      commonMistake: "Using only Call History or only AI Logs. Production diagnosis needs both views.",
      docUrl: TECH_DOCS.routing,
      image: images.routeCreate,
      imageAlt: "Create a new Live Hub routing rule",
    },
  ],

  "agent-builder": [
    {
      id: "ground-with-documents",
      title: "Ground answers with documents",
      objective: "Give the agent a small, trusted knowledge source and prove it uses the source instead of guessing.",
      duration: "7 min",
      path: ["AI Agents", "Documents", "Add document", "Agents", "Attach document"],
      architecture: ["Trusted content", "Document collection", "AI agent", "Grounded answer"],
      before: ["One focused file or approved web page", "Two questions answered by the source", "One question not answered by it"],
      actions: [
        { title: "Choose a focused source", instruction: "Start with a small product guide, FAQ, or approved page. Avoid a mixed archive for the first test." },
        { title: "Create the document", instruction: "Add the file or configure the supported web crawler, then wait until processing is complete." },
        { title: "Attach it to the agent", instruction: "Open the agent and select the new document or collection in its knowledge configuration." },
        { title: "Test known answers", instruction: "Ask the two prepared questions and compare the answer with the source." },
        { title: "Test the boundary", instruction: "Ask the unsupported question and confirm the agent says it does not know or follows your escalation rule." },
      ],
      success: ["Both known answers match the source", "The unsupported answer is not invented", "The agent’s response is concise enough for voice"],
      troubleshooting: [{ problem: "The document seems ignored", fix: "Confirm processing completed, the document is attached to this agent, and the prompt tells the agent when to consult it." }],
      commonMistake: "Uploading a large mixed library before proving one document with three repeatable questions.",
      docUrl: TECH_DOCS.aiAgent,
    },
    {
      id: "add-a-tool",
      title: "Add and verify one tool",
      objective: "Let the agent perform one external action and prove the request and response in logs.",
      duration: "8 min",
      path: ["AI Agents", "Tools", "Add tool", "Test", "Agents", "Attach tool"],
      architecture: ["Agent intent", "Tool request", "External endpoint", "Tool response", "Agent reply"],
      before: ["One safe action", "Endpoint and authentication details", "A known test input and expected output"],
      actions: [
        { title: "Create one focused tool", instruction: "Define a single job such as look up an order or create a ticket. Keep the description explicit about when to use it." },
        { title: "Configure the request", instruction: "Add method, URL, authentication, headers, parameters, and response mapping without exposing secrets in descriptions." },
        { title: "Run the built-in test", instruction: "Use known input and confirm the tool returns the expected output before attaching it to an agent." },
        { title: "Attach it to the agent", instruction: "Open the agent, add the tool, and tell the agent what information it must collect before calling it." },
        { title: "Prove it in logs", instruction: "Run a conversation and inspect the tool request, returned data, elapsed time, and final response in AI Agents logs." },
      ],
      success: ["The tool test succeeds", "The agent calls it only when appropriate", "The request contains correct values", "The final answer reflects the response"],
      troubleshooting: [
        { problem: "4xx or 5xx response", fix: "Check request shape, authentication, endpoint behavior, and response mapping before changing the prompt." },
        { problem: "Status 700 or timeout", fix: "Inspect endpoint reachability and latency, then simplify the call or increase the supported timeout." },
      ],
      commonMistake: "Attaching an untested tool and then blaming the prompt when the endpoint fails.",
      docUrl: TECH_DOCS.aiTools,
    },
    {
      id: "post-call-analysis",
      title: "Capture post-call outcomes",
      objective: "Turn each completed conversation into consistent variables, summaries, and workflow-ready evidence.",
      duration: "7 min",
      path: ["AI Agents", "Agents", "Edit agent", "Post-call analysis"],
      architecture: ["Conversation", "Post-call analysis", "Variables + summary", "Logs or webhook"],
      before: ["Two or three business fields to extract", "A clear definition of success", "A webhook endpoint only if downstream delivery is needed"],
      actions: [
        { title: "Define the outcome", instruction: "Choose a few useful fields such as intent, resolution, case number, sentiment, or handoff reason." },
        { title: "Add extraction rules", instruction: "Describe the expected value and format for each variable so results are consistent." },
        { title: "Add a short summary", instruction: "Request a compact wrap-up that states what the caller wanted, what happened, and the next action." },
        { title: "Configure delivery if needed", instruction: "Add the supported webhook or downstream step and test it with non-sensitive data." },
        { title: "Verify after a call", instruction: "Open AI Agents logs and compare extracted fields with what was actually said." },
      ],
      success: ["Expected variables are present", "The summary is accurate", "Missing information stays empty instead of being invented", "Webhook delivery succeeds when configured"],
      troubleshooting: [{ problem: "Extracted values are inconsistent", fix: "Tighten the field definition and format, then repeat the same conversation. Check the log before changing any integration." }],
      commonMistake: "Extracting dozens of fields before proving the two or three that drive a real business action.",
      docUrl: TECH_DOCS.aiAgent,
    },
    {
      id: "tests-and-logs",
      title: "Build a repeatable test suite",
      objective: "Replace one-off demos with scenarios that reveal regressions after every change.",
      duration: "7 min",
      path: ["AI Agents", "Tests", "Create test", "Run", "Logs"],
      architecture: ["Fixed scenario", "Agent run", "Expected checks", "Log evidence", "Pass or fix"],
      before: ["A happy path", "An unclear request", "A refusal or handoff case", "One tool or document case if used"],
      actions: [
        { title: "Create the scenarios", instruction: "Use realistic wording and one explicit expected outcome for each case." },
        { title: "Run a baseline", instruction: "Execute the suite before changing the agent and save the result." },
        { title: "Inspect every failure", instruction: "Use logs to decide whether the failure came from prompt, model, document retrieval, tool, variable, or test expectation." },
        { title: "Change one layer", instruction: "Make one focused change, rerun the same suite, and compare the result with the baseline." },
        { title: "Keep production gates", instruction: "Require all critical scenarios to pass before publishing or changing routing." },
      ],
      success: ["Every critical behavior has a named scenario", "Failures point to a layer", "The same suite can be rerun after a change"],
      troubleshooting: [{ problem: "A test passes but callers still fail", fix: "Add the real caller wording and conditions as a new regression scenario instead of weakening the existing expected result." }],
      commonMistake: "Changing the agent until one demo works without preserving the scenario as a regression test.",
      docUrl: TECH_DOCS.aiAgent,
    },
    {
      id: "agent-or-flow",
      title: "Choose an agent or controlled flow",
      objective: "Use a flexible agent for judgment and a flow when the business path must be explicit.",
      duration: "8 min",
      path: ["AI Agents", "Agents or Flows"],
      architecture: ["Conversation start", "Agent judgment or flow node", "Tool / knowledge / transition", "Outcome"],
      before: ["The conversation’s required checkpoints", "Which decisions may be flexible", "Which steps must never be skipped"],
      actions: [
        { title: "Choose an agent", instruction: "Use an agent when the job is conversational, the order can vary, and judgment matters more than a fixed sequence." },
        { title: "Choose a flow", instruction: "Use a flow when required steps, approvals, data collection, or handoffs must be explicit and auditable." },
        { title: "Set global behavior", instruction: "Keep tone, safety, language, and universal rules in the shared or global instructions." },
        { title: "Design small nodes", instruction: "Give each flow node one goal and make transition conditions specific. Avoid loops with no exit condition." },
        { title: "Test every exit", instruction: "Run the happy path, every branch, a missing-value case, and the handoff or failure path." },
      ],
      success: ["The chosen structure matches the business constraint", "Every flow node has one purpose", "Every branch and exit has been tested"],
      troubleshooting: [{ problem: "The flow repeats or gets stuck", fix: "Inspect transition conditions, variable updates, and exit paths. Make each condition mutually understandable and give loops a stop condition." }],
      commonMistake: "Building a complex flow for a flexible conversation—or relying on a free-form agent where mandatory checkpoints exist.",
      docUrl: TECH_DOCS.aiAgent,
    },
  ],

  "voice-channel": [
    {
      id: "choose-channel",
      title: "Choose the right voice channel",
      objective: "Select one channel that matches where your calls already live.",
      duration: "3 min",
      path: ["Voice channels"],
      before: ["Where calls originate today", "Whether you need inbound, outbound, or both"],
      actions: [
        { title: "Use a Live Hub number", instruction: "Choose Phone numbers when you want the fastest public phone entry point and do not need to keep an existing carrier." },
        { title: "Use SIP", instruction: "Choose SIP connections for an existing carrier, PBX, contact center, or UC platform." },
        { title: "Use Teams", instruction: "Choose Microsoft Teams when Teams users need calls to or from Live Hub. Connect the tenant first." },
        { title: "Use WebRTC", instruction: "Choose Click-to-Call when calls should start from a website or mobile app." },
        { title: "Use WhatsApp", instruction: "Choose WhatsApp numbers for voice calls from a verified WhatsApp Business number." },
      ],
      success: ["You can name the channel and why it is the simplest fit", "You know which account, tenant, or provider details are required"],
      troubleshooting: [
        { problem: "Two channels both seem possible", fix: "Start with the one that reaches a real test caller fastest. Add the second channel after the first route works." },
      ],
      docUrl: TECH_DOCS.voiceChannels,
      videoId: "y-YQIf4FiG4",
      videoTitle: "Getting Started with Live Hub",
    },
    {
      id: "create-channel",
      title: "Create the connection",
      objective: "Finish the relevant wizard without mixing instructions from another channel.",
      duration: "8 min",
      path: ["Voice channels", "Your channel", "Add new"],
      before: ["The channel decision from lesson 1", "Provider credentials or tenant access when required", "A Live Hub region"],
      actions: [
        { title: "SIP", instruction: "Open SIP connections → Add new SIP connection. Select provider type and provider, choose the region, then enter the wizard’s incoming and outgoing details." },
        { title: "Teams", instruction: "Open Microsoft Teams → Add new connection. Enter a name, region, call limits, and maximum duration, then click Create." },
        { title: "WhatsApp", instruction: "Open WhatsApp numbers → Add new WhatsApp number. Enter a unique name, 6-digit PIN, region, call limits, and duration; then authorize the WhatsApp Business account." },
        { title: "WebRTC", instruction: "Create a SIP connection with Provider Type set to Client Applications and Provider set to Click-to-Call (WebRTC). Prefer authentication code over basic credentials." },
        { title: "Phone number", instruction: "Open Phone numbers and use the plus wizard to select and purchase a DID in the country you need." },
      ],
      success: ["The connection card exists", "The name and region are correct", "The state is moving toward Active or ready"],
      troubleshooting: [
        { problem: "Teams says License Plan not available", fix: "Verify eligible Microsoft 365 licenses before recreating the connection." },
        { problem: "WhatsApp authorization stops", fix: "Confirm an active Facebook account and a verified WhatsApp Business account are available." },
        { problem: "WebRTC authentication is unclear", fix: "Use authentication code for the safer setup. Basic credentials are supported but are not the preferred method." },
      ],
      docUrl: TECH_DOCS.voiceChannels,
      image: images.teamsCreate,
      imageAlt: "Create a Microsoft Teams connection in Live Hub",
    },
    {
      id: "verify-channel",
      title: "Confirm region, state, and limits",
      objective: "Know the channel is ready before you build routing around it.",
      duration: "3 min",
      path: ["Voice channels", "Connection card"],
      before: ["A newly created connection"],
      actions: [
        { title: "Confirm the state", instruction: "Wait for the connection to show Active, Connected, or its equivalent ready state. Teams provisioning can take up to 10 minutes." },
        { title: "Confirm the region", instruction: "Make sure the region matches the bot, routing rule, and other entities that will use this channel." },
        { title: "Review limits", instruction: "Check calls per second, concurrent calls, and maximum call duration. The lowest applicable maximum duration wins." },
        { title: "Keep credentials safe", instruction: "Do not paste provider secrets into notes or screenshots. Store them only in the requested secure fields." },
      ],
      success: ["The connection is ready", "The region matches the destination", "The call limits are acceptable for the test"],
      troubleshooting: [
        { problem: "The state stays Creating", fix: "Open or hover over the state for the reason. For Teams, allow up to 10 minutes before treating it as failed." },
        { problem: "The wrong region was used", fix: "Recreate or edit the connection before continuing, then keep all first-test entities in one region." },
      ],
      docUrl: TECH_DOCS.teams,
      image: images.whatsappCreate,
      imageAlt: "Add new WhatsApp number screen in Live Hub",
    },
    {
      id: "route-channel",
      title: "Route the channel and test",
      objective: "Prove that a call from the selected origin reaches the expected destination.",
      duration: "5 min",
      path: ["Routing", "Routing Rules", "Add new routing rule"],
      before: ["A ready voice channel", "A ready bot, Teams user, contact center, or other destination"],
      actions: [
        { title: "Create the rule", instruction: "Open Routing → Routing Rules and click Add new routing rule." },
        { title: "Set the origin", instruction: "Select the region. Set Type to Call, then choose your phone number, SIP connection, Teams connection, WebRTC connection, or WhatsApp number under Call origin." },
        { title: "Keep the first condition broad", instruction: "For the first controlled test, use the exact called number or * when appropriate. Tighten prefixes after the route works." },
        { title: "Choose the destination", instruction: "Under Route To, choose the bot, phone number, connection, or other destination that should receive the call." },
        { title: "Create and call", instruction: "Click Create, place one test call, and then verify the call in Calls." },
      ],
      success: ["The routing rule is visible", "The origin and destination are correct", "A real test call reaches the destination", "The call appears in Call History"],
      troubleshooting: [
        { problem: "The wrong rule handles the call", fix: "Review other matching rules and their order. Make the test condition more specific." },
        { problem: "The call is rejected", fix: "Check called-number formatting, including the + country code, exact number, prefix, or * pattern." },
      ],
      docUrl: TECH_DOCS.routing,
      image: images.routeCreate,
      imageAlt: "Create a new routing rule in Live Hub",
    },
  ],

  "agent-assist": [
    {
      id: "define-assist",
      title: "Define the assist bot",
      objective: "Create the bot connection that will receive the live transcript.",
      duration: "5 min",
      path: ["Bot connections", "Add new assist bot connection"],
      before: ["An assist-capable bot framework", "A clear assistance goal such as answers, summaries, sentiment, or keyword monitoring"],
      actions: [
        { title: "Open Bot connections", instruction: "Select Bot connections in the Live Hub navigation." },
        { title: "Start an assist connection", instruction: "Click Add new assist bot connection—not Add new voice bot connection." },
        { title: "Choose the framework", instruction: "Select the bot framework that hosts your assist logic and complete its requested connection settings." },
        { title: "Name the outcome", instruction: "Use a name that explains the job, for example Agent-Answers-QA or Wrap-Up-Summary." },
        { title: "Create", instruction: "Save the assist bot and confirm it appears on the Bot connections page." },
      ],
      success: ["The connection is labeled as an assist bot", "Its purpose is clear from the name", "It is available for routing services"],
      troubleshooting: [
        { problem: "You created a voice bot by mistake", fix: "Return to Bot connections and use Add new assist bot connection. The two connection types serve different call roles." },
      ],
      docUrl: TECH_DOCS.agentAssist,
      image: images.assistPicker,
      imageAlt: "Live Hub add new assist bot connection screen",
    },
    {
      id: "choose-assist-path",
      title: "Choose in-path or SIPREC",
      objective: "Use the correct integration pattern for where the call is handled.",
      duration: "4 min",
      path: ["Architecture decision"],
      before: ["Know whether calls already pass through Live Hub"],
      actions: [
        { title: "Calls already in Live Hub", instruction: "Use the in-path method. You only need the assist bot and a routing rule with Agent assist bot enabled under Services." },
        { title: "Calls stay outside Live Hub", instruction: "Use SIPREC. Your phone system acts as the SIPREC client and Live Hub as the SIPREC server so Live Hub receives the live conversation." },
        { title: "For SIPREC", instruction: "Create or prepare the SIP connection that represents the recording path, then make sure the external system sends the SIPREC session to Live Hub." },
        { title: "Write down your selected path", instruction: "Choose one path for the first test. Do not configure both unless your architecture truly contains both call types." },
      ],
      success: ["You can say whether the call is inside or outside Live Hub", "You know whether a SIPREC connection is required"],
      troubleshooting: [
        { problem: "The assist bot receives no transcript", fix: "If the call is outside Live Hub, verify the SIPREC session reaches the Live Hub connection. If inside, verify the service is enabled on the matching routing rule." },
      ],
      docUrl: TECH_DOCS.agentAssist,
      image: images.assistOutside,
      imageAlt: "Agent Assist architecture for calls outside Live Hub using SIPREC",
    },
    {
      id: "attach-assist",
      title: "Attach the bot to routing",
      objective: "Apply the assist bot only to the calls it should monitor.",
      duration: "5 min",
      path: ["Routing", "Routing Rules", "Add or Edit"],
      before: ["A ready assist bot", "A ready call origin", "SIPREC connection if calls are outside Live Hub"],
      actions: [
        { title: "Open the matching rule", instruction: "Create a new routing rule or edit the rule that handles the target call origin." },
        { title: "Set the origin", instruction: "For outside calls, set Type to Call and select the relevant SIP connection as Call origin. For in-path calls, use the existing origin." },
        { title: "Set the normal destination", instruction: "For in-path calls, keep the intended call destination under Route To." },
        { title: "Enable Agent assist bot", instruction: "Under Services, turn on Agent assist bot and select the assist bot connection." },
        { title: "Create or update", instruction: "Save the rule and expand its row to confirm the assist service indicator is active." },
      ],
      success: ["The rule matches the correct origin", "Agent assist bot is enabled", "The intended assist bot is selected"],
      troubleshooting: [
        { problem: "The Agent assist bot option is disabled", fix: "Create the assist bot connection first. Routing can only select an existing assist bot." },
        { problem: "You selected the assist bot as the main destination", fix: "For calls already in Live Hub, keep the normal destination and add the assist bot under Services." },
      ],
      docUrl: TECH_DOCS.agentAssist,
      image: images.assistRoute,
      imageAlt: "Agent Assist service selected in a Live Hub routing rule",
    },
    {
      id: "test-assist",
      title: "Test transcript and assistance",
      objective: "Prove the bot receives the conversation and produces the expected out-of-band result.",
      duration: "6 min",
      path: ["Place test call", "Calls", "Call details"],
      before: ["A saved assist routing rule", "A short test script containing one trigger the bot should recognize"],
      actions: [
        { title: "Plan one trigger", instruction: "Choose a sentence that should cause a clear result—for example, asking for account information or mentioning a monitored keyword." },
        { title: "Place the call", instruction: "Call through the exact origin used in the routing rule and say the trigger naturally during the agent-customer conversation." },
        { title: "Check the assist result", instruction: "Confirm the human agent or configured recipient receives the expected answer, suggestion, alert, or summary." },
        { title: "Inspect the call", instruction: "Open Calls, select the test call, and review participants, transcript/logs, termination, and timing." },
        { title: "Tune one thing", instruction: "If the result is weak, change either the bot instruction or the routing setup—only one variable—then repeat the same test." },
      ],
      success: ["The call is captured", "The transcript contains the trigger phrase", "The assist output reaches the expected recipient", "The output matches the intended job"],
      troubleshooting: [
        { problem: "There is a transcript but no assist output", fix: "The voice path works. Check the assist bot’s trigger logic and out-of-band destination." },
        { problem: "There is no transcript", fix: "Check the routing rule service and, for outside calls, the SIPREC connection before changing the bot logic." },
      ],
      docUrl: TECH_DOCS.callHistory,
      image: images.callSummary,
      imageAlt: "Live Hub call summary used to verify an Agent Assist test call",
    },
  ],

  translation: [
    {
      id: "translation-profile",
      title: "Create the translation profile",
      objective: "Choose when translation begins and create the profile shell.",
      duration: "4 min",
      path: ["Hub+", "Voice translation", "Add new voice translation"],
      before: ["Agent language", "Customer language", "Whether translation should start automatically or by keypad code"],
      actions: [
        { title: "Open Voice translation", instruction: "Expand Hub+ in the navigation and select Voice translation." },
        { title: "Start the wizard", instruction: "Click Add new voice translation." },
        { title: "Name and locate it", instruction: "In General, enter a clear name and select the Live Hub region associated with the call flow." },
        { title: "Choose the speech account", instruction: "Select the AudioCodes speech provider option or your own provider, depending on your account setup." },
        { title: "Choose activation", instruction: "Use Automatic start when one language pair applies to every call. Use Dynamic activation when an agent should select from multiple languages using DTMF." },
      ],
      success: ["The name and region are correct", "The activation mode matches the real call experience", "The wizard advances to Languages"],
      troubleshooting: [
        { problem: "You are unsure which activation mode to use", fix: "Start with Automatic for one fixed language pair. Use Dynamic only when agents must choose a language during the call." },
      ],
      docUrl: TECH_DOCS.translationCreate,
      image: images.translationGeneral,
      imageAlt: "General settings for automatic voice translation in Live Hub",
    },
    {
      id: "translation-languages",
      title: "Set languages and activation",
      objective: "Define exactly who speaks which language and, for dynamic mode, how it starts.",
      duration: "5 min",
      path: ["Voice translation wizard", "Languages"],
      before: ["Exact language locales, not only language names", "DTMF codes if using dynamic activation"],
      actions: [
        { title: "Automatic mode", instruction: "Select one Agent language and one Customer language. Example: agent en-GB and customer fr-FR." },
        { title: "Dynamic mode", instruction: "Add at least two customer-language options. Create a row for each supported language." },
        { title: "Add DTMF activation", instruction: "For every dynamic pair, enter a DTMF code and select the agent and customer languages. At least one activation code is required." },
        { title: "Choose the translation provider", instruction: "Select the available provider—such as Azure, Claude, or OpenAI—for the language pair." },
        { title: "Continue", instruction: "Review every locale and code, then click Next." },
      ],
      success: ["Agent and customer languages are not reversed", "Dynamic mode contains at least two languages", "Every intended pair has a unique DTMF code"],
      troubleshooting: [
        { problem: "Translation goes in the wrong direction", fix: "Recheck which locale is configured as Agent language and which is Customer language." },
        { problem: "Dynamic activation does nothing", fix: "Confirm a DTMF code exists for that exact language pair and note whether customer activation is allowed." },
      ],
      docUrl: TECH_DOCS.translationDynamic,
      image: images.translationDynamic,
      imageAlt: "Dynamic voice translation language and DTMF settings",
    },
    {
      id: "translation-speech",
      title: "Choose speech, voice, and volume",
      objective: "Make both directions understandable and comfortable to listen to.",
      duration: "5 min",
      path: ["Voice translation wizard", "Languages", "Advanced"],
      before: ["A supported STT service", "A supported TTS voice for each locale"],
      actions: [
        { title: "Configure the agent side", instruction: "Choose the agent language, STT service, TTS service, and a matching voice name." },
        { title: "Configure the customer side", instruction: "Choose the customer language, STT service, TTS service, and a matching voice name." },
        { title: "Set volume behavior", instruction: "In Advanced, adjust original-language volume when translation is idle and when translated speech is playing. 0 dB is normal; -31 dB is very low." },
        { title: "Add an activation message", instruction: "Optionally add a short message—maximum 200 characters—so participants know translation is active." },
        { title: "Choose useful features", instruction: "Enable agent or customer barge-in when natural interruption matters. Enable Store call transcript when you need both original and translated text for review." },
      ],
      success: ["Every locale has STT, TTS, and a matching voice", "Original audio is not overpowering translated audio", "Transcript storage follows your privacy and support needs"],
      troubleshooting: [
        { problem: "A voice is missing", fix: "Choose a TTS provider and voice that support the exact configured locale." },
        { problem: "Participants hear two voices too loudly", fix: "Lower the foreign/original language slider while translation is playing, or mute it for the agent when appropriate." },
      ],
      docUrl: TECH_DOCS.translationAutomatic,
      image: images.translationAdvanced,
      imageAlt: "Advanced volume and feature controls for Live Hub voice translation",
    },
    {
      id: "translation-route-test",
      title: "Enable the route and test both ways",
      objective: "Prove the configured call receives clear two-way translation.",
      duration: "6 min",
      path: ["Routing", "Routing Rules", "Add or Edit"],
      before: ["A created translation profile", "A ready call origin and destination", "Two people or recordings that can speak the configured languages"],
      actions: [
        { title: "Open the call’s rule", instruction: "Create or edit the routing rule that matches the target phone number or connection." },
        { title: "Enable Voice translation", instruction: "Under Services, turn on Voice translation and select the profile you created.", note: "Voice translation cannot be enabled together with Agent assist on the same rule." },
        { title: "Save", instruction: "Create or update the rule and expand it to confirm the Voice translation indicator is active." },
        { title: "Run a two-way test", instruction: "Place a call. Have the customer speak first, then the agent. In dynamic mode, enter the configured DTMF code before testing the language pair." },
        { title: "Inspect the result", instruction: "Open Calls and review the Real-time translation transcript. Check that original and translated turns appear in the correct order." },
      ],
      success: ["Translation activates at the expected time", "Both participants hear the other in their configured language", "The transcript identifies the two directions", "The call remains stable through several turns"],
      troubleshooting: [
        { problem: "The Voice translation service is disabled", fix: "Create the translation profile first and make sure Agent assist is not enabled on the same rule." },
        { problem: "Only one direction works", fix: "Check STT, TTS, locale, and voice settings for the failing participant’s side." },
        { problem: "Translation is slow", fix: "Use Call History to compare STT, provider, and TTS timing before changing multiple settings." },
      ],
      docUrl: TECH_DOCS.routing,
      image: images.translationLanguages,
      imageAlt: "Automatic translation language configuration in Live Hub",
    },
  ],

  diagnose: [
    {
      id: "capture-failed-call",
      title: "Capture one failed call",
      objective: "Start with one exact call record so every next check is based on evidence, not guessing.",
      duration: "4 min",
      path: ["Calls", "Call History", "Affected call"],
      before: ["The approximate time of the failure", "Calling or called number", "Permission to view call details"],
      actions: [
        { title: "Reproduce once", instruction: "If it is safe, place one controlled test call and note what you expected versus what actually happened." },
        { title: "Open Call History", instruction: "Go to Calls → Call History and filter by time, calling number, called number, or service until you find the exact attempt." },
        { title: "Copy the identifiers", instruction: "Record the Call ID, timestamp with time zone, calling number, called number, duration, and Completion status." },
        { title: "Keep related records together", instruction: "If alternate routing or a transfer created several records, search for records with the same SID and treat them as one sequence." },
      ],
      success: ["You have the exact Call ID", "The timestamp includes a time zone", "You can describe expected versus observed behavior in one sentence"],
      troubleshooting: [
        { problem: "The call is not in history", fix: "Broaden the time range, remove one filter at a time, and confirm you are looking in the correct account and region." },
        { problem: "There are several records", fix: "Compare the SID, start time, routing group, and transfer details before choosing one record in isolation." },
      ],
      docUrl: TECH_DOCS.callHistory,
      image: images.callHistory,
      imageAlt: "Live Hub Call History with filters and call records",
    },
    {
      id: "read-completion-status",
      title: "Read the outcome before the logs",
      objective: "Use Completion status and the call summary to identify the first likely failing layer.",
      duration: "4 min",
      path: ["Calls", "Call History", "Completion status"],
      before: ["The call record from lesson 1", "The exact Completion status text"],
      actions: [
        { title: "Read the status literally", instruction: "Copy the Completion status exactly. A SIP code, Bot Err, STT Err, TTS Err, limit message, or normal Bye each points to a different starting layer." },
        { title: "Decide whether it is expected", instruction: "Statuses such as caller cancel, busy, normal call clear, a configured maximum duration, or no-user-input can be normal lifecycle events." },
        { title: "Name the first owner", instruction: "Choose one starting layer: routing/telephony, Microsoft Teams, speech, AI agent, tool or webhook, account limit, or expected behavior." },
        { title: "Open the matching glossary entry", instruction: "Use the Academy Troubleshooting search to match the exact status or the closest symptom and read What it means before changing configuration." },
      ],
      success: ["The exact status is recorded", "You know whether it may be expected", "You selected one first area to investigate"],
      troubleshooting: [
        { problem: "The status says Unknown error", fix: "Continue with the timeline evidence in the next lesson and collect the Call ID for support; do not change several systems at once." },
        { problem: "The status is blank or unclear", fix: "Use the call summary, participant sequence, service indicators, and timestamps to find the last successful stage." },
      ],
      docUrl: TECH_DOCS.callHistory,
      image: images.callSummary,
      imageAlt: "Live Hub call summary showing completion and enabled services",
    },
    {
      id: "inspect-failing-layer",
      title: "Inspect the right evidence",
      objective: "Open only the evidence that can prove or disprove the suspected layer.",
      duration: "6 min",
      path: ["Calls", "Call details", "Recording / Transcript / AI logs / SIP Ladder"],
      before: ["The first suspected layer", "Access to the call details"],
      actions: [
        { title: "For signaling or routing", instruction: "Open the SIP Ladder. Find which side sent the final failure response and check whether the request reached the intended destination." },
        { title: "For speech or audio", instruction: "Listen to the recording, compare the transcript with what was spoken, and review voice quality plus separate STT and TTS latency values." },
        { title: "For AI behavior", instruction: "Open AI Agent logs and follow the turn where behavior changed. Check recognized input, model response, tool calls, document activity, and Flow transitions." },
        { title: "For broad failures", instruction: "Open Alarms and Alarm History. Check capacity, connectivity, voice quality, balance, and account state around the same timestamp." },
        { title: "Write the finding", instruction: "Capture one evidence sentence, for example: ‘The carrier returned 403’ or ‘STT websocket closed before the first transcript turn.’" },
      ],
      success: ["You opened evidence for the suspected layer", "You know which system produced the first failure", "You wrote one evidence-backed finding"],
      troubleshooting: [
        { problem: "There is no recording", fix: "Recordings are only available when enabled and still inside retention. Use the transcript, logs, SIP Ladder, and call metadata instead." },
        { problem: "Support cannot see the content", fix: "Sharing is off by default. Share the relevant transcript or AI agent logs, or download the exact files and send them yourself." },
      ],
      docUrl: TECH_DOCS.callHistory,
      image: images.sipLadder,
      imageAlt: "Live Hub SIP Ladder used to identify which side returned an error",
    },
    {
      id: "apply-one-fix",
      title: "Change one layer and retest",
      objective: "Apply the smallest evidence-backed correction and prove whether it changed the result.",
      duration: "5 min",
      path: ["Affected configuration", "Edit", "Save", "Test call"],
      before: ["One confirmed or strongly suspected cause", "A reversible configuration change"],
      actions: [
        { title: "Choose the smallest fix", instruction: "Examples: correct the called-number pattern, align regions, update one SIP credential, select the right STT locale, repair one tool parameter, or lower a burst rate." },
        { title: "Record the original value", instruction: "Before saving, note the previous setting so you can restore it if the test becomes worse." },
        { title: "Change only one variable", instruction: "Save one correction. Avoid changing routing, speech, and agent instructions in the same test because the successful cause will be impossible to prove." },
        { title: "Repeat the same call", instruction: "Use the same origin, destination, test phrase, and expected result whenever possible." },
        { title: "Compare records", instruction: "Compare the new Completion status, call path, transcript, latency, and logs with the original failed attempt." },
      ],
      success: ["Only one meaningful variable changed", "A new Call ID exists", "You can say whether the change fixed, changed, or did not affect the failure"],
      troubleshooting: [
        { problem: "The symptom changed", fix: "That is useful evidence. Search the new exact status and continue from the new first failing layer." },
        { problem: "The same failure remains", fix: "Restore the setting if necessary, record that the cause was disproved, and move to the next most likely cause." },
      ],
      docUrl: TECH_DOCS.callHistory,
      image: images.botLatency,
      imageAlt: "Live Hub latency view for comparing bot and speech stages",
    },
    {
      id: "escalate-cleanly",
      title: "Escalate with a complete case",
      objective: "Give support enough evidence to investigate immediately while sharing only what is necessary.",
      duration: "4 min",
      path: ["Help Center", "Contact support"],
      before: ["Call ID and timestamp", "Observed versus expected result", "Evidence from the failing layer", "The change already tested"],
      actions: [
        { title: "Try the right assistant first", instruction: "Use the support assistant for documentation questions. For AI Agents, use Build with AI because the AI Assistant can inspect, simulate, edit, and run tests." },
        { title: "Choose severity by impact", instruction: "Open Help Center → Contact support and select Low, Medium, High, or Urgent based on the real service impact. Premium support customers should use the Service Portal." },
        { title: "Attach the exact evidence", instruction: "Include Call ID, timestamp and time zone, numbers, connection/agent/Flow name, exact status, relevant SIP Ladder or logs, and what you already tried." },
        { title: "Share content deliberately", instruction: "Transcript sharing is enabled per bot connection. AI agent log sharing is account-wide. Recordings have no standing-access switch and must be sent manually." },
        { title: "Never send secrets", instruction: "Do not include passwords, API keys, client secrets, or bearer tokens in the case." },
      ],
      success: ["The ticket has a clear impact and severity", "The exact identifiers and evidence are attached", "No secrets or unrelated call content were shared"],
      troubleshooting: [
        { problem: "The recording or transcript may expire", fix: "Download anything the investigation depends on before its retention period ends." },
        { problem: "You are unsure what to share", fix: "Start with metadata and the smallest relevant excerpt. Add call content only when it is needed for the investigation." },
      ],
      docUrl: TECH_DOCS.support,
      image: images.callHistory,
      imageAlt: "Live Hub Call History used to download evidence for support",
    },
  ],
};
