import type { Lesson } from "./lesson-data";
import { TECH_DOCS } from "./techdocs";

/**
 * Outcome courses added from the complete Live Hub 2.19.2 manual.
 * Vendor-specific fields and exhaustive parameter tables remain in Expert
 * Reference; these missions cover the shortest verifiable customer workflow.
 */
export const supplementalLessonsByTrack: Record<string, Lesson[]> = {
  "bot-connect": [
    {
      id: "bot-choose-framework",
      title: "Choose the connection that fits your bot",
      objective: "Identify the correct framework and collect only the credentials that connection requires.",
      duration: "5 min",
      path: ["Bot connections", "Add new voice bot connection"],
      architecture: ["Existing bot", "Bot connection", "Speech", "Live Hub call"],
      before: ["A published or reachable bot", "Administrator access to its platform", "The intended Live Hub account and region"],
      actions: [
        { title: "Name the framework", instruction: "Choose Live Hub AI Agent, AudioCodes Bot API, Copilot Studio, Microsoft Bot Framework, Dialogflow CX or ES, Google CX Agent Studio, Amazon Lex, RASA, or Additional bot frameworks." },
        { title: "Collect the matching credentials", instruction: "Use only the credential set required by that framework. For example, Bot Framework uses a Direct Line secret; Amazon Lex uses AWS access credentials." },
        { title: "Confirm speech ownership", instruction: "Dialogflow supplies its own speech services. Most other frameworks require you to select STT and TTS in Live Hub." },
        { title: "Write the test outcome", instruction: "Choose one phrase the bot must understand and one short response it must return before telephony is added." },
      ],
      success: ["The framework is unambiguous", "Required credentials are available", "You know whether Live Hub or the framework supplies speech"],
      troubleshooting: [{ problem: "Your framework is not listed", fix: "Use Additional bot frameworks only when the bot implements the AudioCodes Bot API. Do not select a visually similar framework." }],
      commonMistake: "Beginning the wizard before the bot is published and its exact authentication method is known.",
      docUrl: TECH_DOCS.botConnections,
    },
    {
      id: "bot-create-connection",
      title: "Connect the bot and give it speech",
      objective: "Create one voice bot connection and make it ready for a direct test.",
      duration: "7 min",
      path: ["Bot connections", "Add new voice bot connection", "Framework"],
      architecture: ["Caller audio", "STT", "Bot", "TTS", "Caller audio"],
      before: ["The framework decision", "Bot credentials", "A language and voice", "Speech provider credentials when using your own subscription"],
      actions: [
        { title: "Select the framework", instruction: "Open Bot connections, select Add new voice bot connection, and choose the exact framework." },
        { title: "Enter the bot details", instruction: "Add the requested endpoint, environment, region, secret, or authentication fields from the bot platform." },
        { title: "Select STT and TTS", instruction: "Choose a speech-to-text service, language, text-to-speech service, and matching voice unless the framework supplies its own speech." },
        { title: "Create the connection", instruction: "Save it, then reopen Details and Settings to confirm the name, framework, region, and speech choices." },
      ],
      success: ["The bot connection appears in Bot connections", "Its framework and region are correct", "Speech services match the intended language"],
      troubleshooting: [
        { problem: "The connection cannot authenticate", fix: "Verify the framework-specific credential at its source. Do not rotate several secrets at once." },
        { problem: "A speech service is missing", fix: "Add your subscription under Speech providers first, or select an available AudioCodes-provided service." },
      ],
      commonMistake: "Choosing a voice whose locale does not match the speech-to-text language.",
      docUrl: TECH_DOCS.botConnections,
    },
    {
      id: "bot-test-before-routing",
      title: "Prove the bot before routing a call",
      objective: "Separate bot and speech quality from phone-channel and routing problems.",
      duration: "6 min",
      path: ["Bot connections", "Connection card", "Test call"],
      architecture: ["Browser", "Bot connection", "Bot response", "Evidence"],
      before: ["A saved bot connection", "Browser microphone permission", "One known question and expected answer"],
      actions: [
        { title: "Open the direct test", instruction: "Use the phone icon on the bot connection and confirm the correct microphone and speaker." },
        { title: "Run the known scenario", instruction: "Say the prepared phrase and listen for the expected short answer." },
        { title: "Check turn taking", instruction: "Verify silence detection, interruption behavior, and DTMF only if the bot uses them." },
        { title: "Enable only needed features", instruction: "After the baseline works, use Features for transcript, recording, transfer, background music, or failover." },
      ],
      success: ["The direct browser call connects", "The bot understands the known phrase", "The expected response is spoken clearly"],
      troubleshooting: [{ problem: "The bot works in text but not voice", fix: "Inspect microphone permission, STT language, recognized text, TTS voice, and speech latency before touching routing." }],
      commonMistake: "Creating a phone route before the direct bot test passes.",
      docUrl: TECH_DOCS.botTest,
    },
  ],

  "speech-provider": [
    {
      id: "speech-choose-provider",
      title: "Choose speech for one real conversation",
      objective: "Pick STT and TTS by language, latency, voice, compliance, and ownership—not by brand familiarity.",
      duration: "5 min",
      path: ["Speech providers"],
      architecture: ["Caller audio", "STT", "Bot text", "TTS", "Caller"],
      before: ["Target language and locale", "Latency target", "Preferred voice", "Decision to use AudioCodes billing or your own provider subscription"],
      actions: [
        { title: "Define the call", instruction: "Write the language, accent, expected noise level, and whether callers interrupt frequently." },
        { title: "Choose STT", instruction: "Select a provider and model that support the locale and turn-taking behavior. Current options include Microsoft, Google, Deepgram, Soniox, ElevenLabs, Speechmatics, OpenAI, and custom integration choices." },
        { title: "Choose TTS", instruction: "Select a provider and voice that support the same locale. Keep the first test to one voice." },
        { title: "Choose ownership", instruction: "Use an included service when available, or add your provider account when policy, region, features, or commercial terms require it." },
      ],
      success: ["One STT model and one TTS voice are selected", "Both support the target locale", "The ownership and billing choice is understood"],
      troubleshooting: [{ problem: "There are too many provider options", fix: "Use one caller locale, one expected environment, and one latency goal to create a shortlist. Move model tables to Expert Reference." }],
      docUrl: TECH_DOCS.speechProviders,
    },
    {
      id: "speech-add-provider",
      title: "Add your provider safely",
      objective: "Create a reusable speech provider without exposing credentials or mixing environments.",
      duration: "6 min",
      path: ["Speech providers", "Add speech provider"],
      architecture: ["Provider account", "Authentication key", "Live Hub provider", "Bot connection"],
      before: ["Provider endpoint or region", "Authentication key", "A name that identifies vendor and environment"],
      actions: [
        { title: "Select the vendor", instruction: "Open Speech providers, add a provider, and choose the exact vendor or Custom integration." },
        { title: "Name the environment", instruction: "Use a name such as Deepgram-Production-EU so builders do not select a test subscription by mistake." },
        { title: "Enter secure fields", instruction: "Add the authentication key, endpoint, host, region, or account fields requested by that vendor. Never place a key in the description." },
        { title: "Create and reopen", instruction: "Save the provider and confirm its displayed vendor, region, and purpose." },
      ],
      success: ["The provider appears in Speech providers", "Its name identifies vendor and environment", "No secret appears in notes or screenshots"],
      troubleshooting: [{ problem: "Authentication fails", fix: "Verify the key, endpoint, subscription region, and provider permissions at the source. Rotate only the affected credential." }],
      commonMistake: "Using one ambiguous provider name for test and production credentials.",
      docUrl: TECH_DOCS.speechProviders,
    },
    {
      id: "speech-prove-quality",
      title: "Prove recognition, voice, and latency",
      objective: "Use one repeatable call to decide whether the speech configuration is ready.",
      duration: "7 min",
      path: ["Bot connections", "Settings", "Test call", "Calls"],
      architecture: ["Known phrase", "Transcript", "Spoken answer", "Latency evidence"],
      before: ["A bot connection using the provider", "A 20-second script with a name, number, and interruption"],
      actions: [
        { title: "Attach the provider", instruction: "Edit the bot connection and choose the new STT or TTS provider, model, language, and voice." },
        { title: "Run the same script", instruction: "Say the prepared phrase naturally, include the name and number, and interrupt one response." },
        { title: "Compare speech evidence", instruction: "Check the recognized transcript against what was said and listen for pronunciation, pace, and interruption behavior." },
        { title: "Read latency", instruction: "Open the call and compare STT, bot, and TTS delay. Tune only the stage that is slow or inaccurate." },
      ],
      success: ["The transcript matches the important words", "The voice matches the locale", "You can identify the slowest stage from call evidence"],
      troubleshooting: [{ problem: "The whole call feels slow", fix: "Use the separate STT, bot, and TTS timing before changing models. The slowest measured stage owns the first experiment." }],
      commonMistake: "Changing STT, TTS, and the bot model in one test, which makes the improvement impossible to attribute.",
      docUrl: TECH_DOCS.callHistory,
    },
  ],

  "click-to-call": [
    {
      id: "web-call-create-channel",
      title: "Create the web calling channel",
      objective: "Create one Click-to-call connection for a controlled browser test.",
      duration: "6 min",
      path: ["Voice channels", "SIP connections", "Add new SIP connection"],
      architecture: ["Web page", "WebRTC", "Click-to-call connection", "Live Hub"],
      before: ["A test web page", "The target Live Hub region", "A destination bot or voice service"],
      actions: [
        { title: "Choose the correct provider type", instruction: "Create a SIP connection with Provider type set to Client Applications and Provider set to Click-to-Call (WebRTC)." },
        { title: "Name and locate it", instruction: "Use a clear environment name and the same region as the destination and future routing rule." },
        { title: "Choose authentication", instruction: "Prefer short-lived authentication codes. Use fixed credentials only when your architecture and security review require them." },
        { title: "Create the connection", instruction: "Save it and record the connection details needed by the widget or SDK." },
      ],
      success: ["A Click-to-call connection exists", "Its region matches the destination", "The authentication method is intentional"],
      troubleshooting: [{ problem: "You created a Generic SIP trunk", fix: "Recreate it under Client Applications → Click-to-Call (WebRTC); a carrier trunk is a different channel." }],
      docUrl: TECH_DOCS.clickToCall,
    },
    {
      id: "web-call-add-client",
      title: "Put the call button in a real page",
      objective: "Connect the provided widget or SDK to one visible call action.",
      duration: "8 min",
      path: ["Click-to-call", "Web widget or SDK"],
      architecture: ["Call button", "Authentication", "WebRTC session", "Live Hub"],
      before: ["The Click-to-call connection", "A development page served over HTTPS", "Back-end access if generating authentication codes"],
      actions: [
        { title: "Choose widget or SDK", instruction: "Use the JavaScript widget for the fastest branded button. Use the Web SDK when the product needs custom call controls." },
        { title: "Add the client settings", instruction: "Connect the page to the Click-to-call service using the connection information from Live Hub." },
        { title: "Protect authentication", instruction: "When using authentication codes, generate them on your back end. Do not expose API client secrets in browser code." },
        { title: "Allow media", instruction: "Serve the page securely and allow microphone access when the browser requests it." },
      ],
      success: ["The call button appears", "No secret is present in browser source", "The browser can request microphone access and start a session"],
      troubleshooting: [{ problem: "The browser blocks audio", fix: "Confirm HTTPS, microphone permission, supported browser behavior, and an explicit user click before starting media." }],
      commonMistake: "Embedding a long-lived secret in JavaScript instead of generating a short-lived authentication code on the server.",
      docUrl: TECH_DOCS.clickToCall,
    },
    {
      id: "web-call-route-prove",
      title: "Route and prove the browser call",
      objective: "Make one website call reach the intended destination and appear in Calls.",
      duration: "6 min",
      path: ["Routing", "Routing Rules", "Add new routing rule"],
      architecture: ["Browser", "Click-to-call", "Route", "Destination", "Calls"],
      before: ["A working call button", "A ready bot or voice destination", "Both in the same region"],
      actions: [
        { title: "Create the route", instruction: "Use the Click-to-call connection as Call origin and select the intended bot or service under Route To." },
        { title: "Keep the first rule exact", instruction: "Avoid optional services and broad conditions until the baseline call succeeds." },
        { title: "Place the browser call", instruction: "Use the real page, allow the microphone, and complete the prepared short scenario." },
        { title: "Open Calls", instruction: "Confirm the route, destination, duration, completion status, transcript, and audio evidence when enabled." },
      ],
      success: ["The browser call reaches the intended destination", "A call record appears", "The selected routing rule is visible in the evidence"],
      troubleshooting: [{ problem: "The WebRTC session opens but nothing answers", fix: "The channel is alive. Check routing, region, destination readiness, and the exact origin used by the rule." }],
      docUrl: TECH_DOCS.clickToCall,
    },
  ],

  whatsapp: [
    {
      id: "whatsapp-prepare",
      title: "Prepare a WhatsApp voice number",
      objective: "Confirm the Meta assets and ownership needed before Live Hub starts authorization.",
      duration: "5 min",
      path: ["Voice channels", "WhatsApp numbers"],
      architecture: ["WhatsApp caller", "Meta business", "WhatsApp number", "Live Hub"],
      before: ["An active Facebook account", "Access to the WhatsApp Business account", "A number eligible for the integration", "The intended Live Hub region"],
      actions: [
        { title: "Confirm ownership", instruction: "Identify the Meta business and WhatsApp Business account that should own the number. Use an administrator who can approve the connection." },
        { title: "Prepare the number", instruction: "Confirm the phone number is eligible and that you can complete any Meta verification step." },
        { title: "Choose the Live Hub account", instruction: "Check Current account and region before beginning, because the connection and routing will belong there." },
        { title: "Choose a six-digit PIN", instruction: "Prepare the PIN requested by the Live Hub connection flow and store it securely." },
      ],
      success: ["The correct Meta business is identified", "The number is eligible", "The Live Hub account and region are confirmed"],
      troubleshooting: [{ problem: "You cannot select the business or number", fix: "Verify Meta administrator access, business verification, number ownership, and whether the number is already connected elsewhere." }],
      docUrl: TECH_DOCS.whatsapp,
    },
    {
      id: "whatsapp-authorize",
      title: "Connect and authorize the number",
      objective: "Create the Live Hub WhatsApp connection and finish Meta authorization without switching accounts midway.",
      duration: "7 min",
      path: ["WhatsApp numbers", "Add new WhatsApp number"],
      architecture: ["Live Hub request", "Meta authorization", "Connected number"],
      before: ["The preparation checklist", "Meta administrator session", "The six-digit PIN"],
      actions: [
        { title: "Add the number", instruction: "Enter a unique connection name, six-digit PIN, region, call limits, and maximum call duration." },
        { title: "Authorize with Meta", instruction: "Sign in to the intended Facebook account and approve the requested WhatsApp Business assets." },
        { title: "Select the exact number", instruction: "Choose the intended business account and phone number; verify the displayed identity before confirming." },
        { title: "Wait for ready state", instruction: "Return to WhatsApp numbers and confirm the connection is active before creating routing." },
      ],
      success: ["The intended WhatsApp number appears in Live Hub", "Authorization completed for the correct business", "The connection is ready"],
      troubleshooting: [{ problem: "Authorization returns to the wrong account", fix: "Stop, sign out of unintended Meta sessions, and restart with the administrator of the correct business." }],
      commonMistake: "Approving the first Meta business shown without verifying the business and phone number names.",
      docUrl: TECH_DOCS.whatsapp,
    },
    {
      id: "whatsapp-route-call",
      title: "Route and prove a WhatsApp call",
      objective: "Make one WhatsApp voice call reach the intended AI or voice destination.",
      duration: "6 min",
      path: ["Routing", "Routing Rules", "Add new routing rule"],
      architecture: ["WhatsApp caller", "WhatsApp number", "Route", "Bot", "Calls"],
      before: ["A ready WhatsApp number", "A ready bot or voice destination", "One WhatsApp-enabled test phone"],
      actions: [
        { title: "Create the route", instruction: "Choose the WhatsApp number as the Call origin and select the intended bot or destination under Route To." },
        { title: "Keep services off", instruction: "Use a clean baseline before adding recording, translation, transfer behavior, or Agent Assist." },
        { title: "Place the call", instruction: "Call from WhatsApp, complete the known scenario, and end normally." },
        { title: "Inspect evidence", instruction: "Open Calls and confirm the origin, matched route, destination, completion status, and transcript when enabled." },
      ],
      success: ["The WhatsApp call reaches the intended destination", "The call appears in Calls", "The route and result are understandable from evidence"],
      troubleshooting: [{ problem: "The call reaches Live Hub but audio fails", fix: "Check codec and media evidence, region, and the call record before changing Meta authorization." }],
      docUrl: TECH_DOCS.whatsapp,
    },
  ],

  outbound: [
    {
      id: "outbound-enable",
      title: "Prepare one safe outbound call",
      objective: "Enable dialout with the correct plan, API identity, bot, and limits.",
      duration: "7 min",
      path: ["Bot connections", "Edit", "Outbound Calling"],
      architecture: ["Dialer", "Live Hub", "Voice channel", "Person", "Bot"],
      before: ["A ready bot connection", "A controlled destination number", "A SIP connection or enabled AudioCodes-supplied calling number", "Permission to create an API client"],
      actions: [
        { title: "Check the voice channel", instruction: "Choose the SIP connection or calling number Live Hub will use. AudioCodes-supplied outbound PSTN calling requires an Essential plan and AudioCodes enablement." },
        { title: "Open Outbound Calling", instruction: "Edit the bot connection and select its Outbound Calling tab." },
        { title: "Create the API client", instruction: "Use Create API client and copy the client ID and secret immediately; the secret is not shown again." },
        { title: "Set only needed options", instruction: "Choose whether recognition starts on connect and whether the bot receives the dialout initiated event." },
      ],
      success: ["Outbound Calling is enabled on the intended bot", "The API client secret is stored safely", "The channel and account are eligible for the test"],
      troubleshooting: [{ problem: "Outbound PSTN is unavailable", fix: "Confirm the Essential plan, positive balance, and AudioCodes enablement for supplied numbers. Adding credit alone does not enable it." }],
      commonMistake: "Assuming an Essential plan automatically enables outbound PSTN through AudioCodes-supplied numbers.",
      docUrl: TECH_DOCS.outboundCalling,
    },
    {
      id: "outbound-route",
      title: "Create the outbound route",
      objective: "Tell Live Hub which channel places calls requested by this bot.",
      duration: "5 min",
      path: ["Routing", "Routing Rules", "Add new routing rule"],
      architecture: ["Bot connection", "Routing rule", "SIP or number", "Destination"],
      before: ["The enabled bot connection", "A ready outbound voice channel", "An agreed target-number format"],
      actions: [
        { title: "Start with the bot", instruction: "Create a Call rule and select the bot connection as Call origin." },
        { title: "Select the calling channel", instruction: "Route to the SIP connection that places the call or the phone number Live Hub should call from." },
        { title: "Match the number format", instruction: "Use the target format expected by the carrier or channel, normally tel:+ followed by E.164 digits for the API request." },
        { title: "Save and read it back", instruction: "Confirm the rule says: calls initiated by this bot leave through this exact channel." },
      ],
      success: ["The bot is the route origin", "The intended outbound channel is the destination", "The target number format is known"],
      troubleshooting: [{ problem: "The request is accepted but no call leaves", fix: "Check that the outbound route exists, the bot matches the request, and the destination channel is ready." }],
      docUrl: TECH_DOCS.outboundCalling,
    },
    {
      id: "outbound-trigger-prove",
      title: "Trigger and prove the dialout",
      objective: "Place one controlled API call and follow it from request to final status.",
      duration: "8 min",
      path: ["Dialout API", "POST /api/v1/actions/dialout"],
      architecture: ["POST dialout", "Call ID", "Phone answers", "Bot", "Final status"],
      before: ["API client ID and secret", "Bot connection ID", "Controlled target in tel:+ format", "The saved route"],
      actions: [
        { title: "Use the right authentication", instruction: "Call POST /api/v1/actions/dialout with HTTP Basic authentication. This endpoint does not use the OAuth bearer token used by the main REST API." },
        { title: "Send the minimum body", instruction: "Provide the bot connection ID and target URI, such as tel:+123456789. Add metadata only after the baseline works." },
        { title: "Run the portal test too", instruction: "Use Test Outbound Call on the bot connection to separate API-client problems from route or carrier problems." },
        { title: "Follow the evidence", instruction: "Record the returned call ID and conversation ID, then inspect Call History and any configured status notifications." },
      ],
      success: ["The API request returns an identifier", "The controlled phone rings", "The bot handles the answered call", "A final call status is visible"],
      troubleshooting: [
        { problem: "The API returns 401", fix: "Use Basic authentication with the dialout API client, not an OAuth bearer token." },
        { problem: "The portal test works but the API call fails", fix: "The voice path works. Check the API client, Basic header, bot ID, target URI, and request body." },
      ],
      commonMistake: "Using REST API OAuth authentication on the dialout endpoint.",
      docUrl: TECH_DOCS.outboundCalling,
    },
  ],

  campaigns: [
    {
      id: "campaign-design",
      title: "Design a controlled outbound campaign",
      objective: "Define one audience, one bot outcome, and one safe operating window before importing targets.",
      duration: "5 min",
      path: ["Hub+", "Outbound automation", "Add campaign"],
      architecture: ["Target list", "Campaign", "Bot", "Outbound route", "Result"],
      before: ["A ready outbound bot and route", "Permission to contact the targets", "A small approved test list", "Time zone and calling window"],
      actions: [
        { title: "Name the business outcome", instruction: "Choose one result such as appointment confirmation, reminder, or consented follow-up." },
        { title: "Choose the bot", instruction: "Use the bot connection that already passes a direct outbound test." },
        { title: "Set timing and behavior", instruction: "Choose the relevant time zone, calling window, retry behavior, and completion rules for the audience." },
        { title: "Start with a tiny pilot", instruction: "Use a few approved internal or controlled targets before loading a production audience." },
      ],
      success: ["The campaign has one measurable outcome", "The bot and route already work", "The first audience is small and approved"],
      troubleshooting: [{ problem: "The campaign design has several goals", fix: "Split it. One campaign should have one audience, one expected conversation, and one result to measure." }],
      docUrl: TECH_DOCS.outboundAutomation,
    },
    {
      id: "campaign-load-targets",
      title: "Load targets without surprises",
      objective: "Create or import a clean target list and verify the first records before calling.",
      duration: "7 min",
      path: ["Outbound automation", "Campaign", "Targets"],
      architecture: ["Approved CSV", "Targets", "Validation", "Ready campaign"],
      before: ["A small CSV or manual target list", "Phone numbers in the required format", "Any variables the bot expects"],
      actions: [
        { title: "Define one sample target", instruction: "Add one target manually first so the required fields and number format are clear." },
        { title: "Prepare the import", instruction: "Match the campaign's supported columns and include only the variables the bot needs." },
        { title: "Import the pilot", instruction: "Load the small approved list and review any rejected or incomplete rows." },
        { title: "Inspect the first records", instruction: "Confirm number, time zone, metadata, and status before starting the campaign." },
      ],
      success: ["Every pilot target is visible", "Numbers use the intended format", "Required bot variables are populated"],
      troubleshooting: [{ problem: "Rows are rejected", fix: "Compare the CSV headers and value types with the campaign fields, then fix one sample row before reimporting the list." }],
      commonMistake: "Importing the complete production list before one manual target proves the required shape.",
      docUrl: TECH_DOCS.outboundAutomation,
    },
    {
      id: "campaign-run-monitor",
      title: "Run the pilot and read every outcome",
      objective: "Launch a small campaign, monitor progress, and explain the final status of each target.",
      duration: "8 min",
      path: ["Outbound automation", "Campaign", "Run"],
      architecture: ["Run", "Progress", "Target status", "Calls", "Decision"],
      before: ["The validated pilot targets", "A ready bot, route, and voice channel", "An owner watching the run"],
      actions: [
        { title: "Start the pilot", instruction: "Run only the controlled campaign and keep its size within the account and connection call limits." },
        { title: "Watch progress", instruction: "Use the campaign status and progress view to see queued, active, completed, failed, or otherwise resolved targets." },
        { title: "Open failed targets", instruction: "For each failure type, open the related call record and identify whether the first issue is API, routing, carrier, answer detection, or bot behavior." },
        { title: "Decide whether to scale", instruction: "Expand the audience only after the pilot's success rate, call experience, retry behavior, and evidence meet the agreed gate." },
      ],
      success: ["The pilot completes", "Every failed target has an understood status", "A clear go, tune, or stop decision is recorded"],
      troubleshooting: [{ problem: "Many targets fail at once", fix: "Pause or lock the campaign, inspect the first shared failure, and correct the common layer before retrying." }],
      docUrl: TECH_DOCS.outboundAutomation,
    },
  ],

  "call-features": [
    {
      id: "features-evidence",
      title: "Choose the evidence each call should produce",
      objective: "Enable transcripts and recordings deliberately, with plan and retention understood.",
      duration: "6 min",
      path: ["Bot connections", "Edit", "Features"],
      architecture: ["Call", "Transcript or recording", "Retention", "Authorized user"],
      before: ["A bot connection", "Privacy approval", "Required retention period", "An Essential plan when recording is needed"],
      actions: [
        { title: "Choose transcript or recording", instruction: "Use transcripts when searchable conversation text is enough. Add recording only when the audio itself is required." },
        { title: "Enable per bot", instruction: "Turn on Call Transcript and the required Call Recording mode in the bot connection's Features tab." },
        { title: "Confirm retention", instruction: "The manual's defaults are seven days for transcripts and thirty days for recordings; verify the account settings that apply to your deployment." },
        { title: "Place one test call", instruction: "Open Call History and confirm the expected artifact appears and is accessible to the intended user." },
      ],
      success: ["The right evidence is enabled", "Retention and plan requirements are understood", "A test call produces the expected artifact"],
      troubleshooting: [{ problem: "A recording is missing", fix: "Confirm the Essential plan, recording mode, matched bot or route, completed call, permissions, and retention window." }],
      commonMistake: "Enabling recording everywhere without a privacy purpose, access model, or retention decision.",
      docUrl: TECH_DOCS.callTranscript,
    },
    {
      id: "features-transfer",
      title: "Transfer a caller without losing context",
      objective: "Configure one supported transfer path and prove the destination receives the expected call and context.",
      duration: "8 min",
      path: ["Bot connections", "Edit", "Features", "Call transfer"],
      architecture: ["Caller", "Bot", "Transfer", "Human destination", "Transfer evidence"],
      before: ["A verified transfer destination", "Provider support for INVITE or REFER", "The context or SIP headers the human side needs"],
      actions: [
        { title: "Choose the transfer method", instruction: "Match INVITE or REFER to the SIP provider or contact center's supported behavior." },
        { title: "Configure the target", instruction: "Set the destination number or routing behavior and add only approved custom SIP headers." },
        { title: "Handle failure", instruction: "Define what the bot should do when transfer setup fails or the destination cannot accept the call." },
        { title: "Run the full test", instruction: "Start with a real caller, trigger transfer, verify the human side receives the call and context, then inspect all related call records." },
      ],
      success: ["The transfer reaches the intended destination", "Required context arrives", "Failed transfer behavior is safe and understandable"],
      troubleshooting: [{ problem: "The transfer starts but does not complete", fix: "Inspect the transfer call record and SIP Ladder, then compare INVITE or REFER behavior with the provider requirement." }],
      docUrl: TECH_DOCS.callTransfer,
    },
    {
      id: "features-failover",
      title: "Give failed calls a safe next move",
      objective: "Create one failover action that protects the caller without hiding the original failure.",
      duration: "7 min",
      path: ["Bot connections", "Edit", "Features", "Failover actions"],
      architecture: ["Primary bot", "Failure", "Failover action", "Safe destination", "Evidence"],
      before: ["A defined primary failure", "A ready fallback destination", "A message or transfer behavior appropriate for callers"],
      actions: [
        { title: "Choose the failure", instruction: "Target one real failure condition rather than sending every unsuccessful call to the same place." },
        { title: "Choose the safe action", instruction: "Configure the supported fallback behavior, such as a message, transfer, or alternate destination." },
        { title: "Keep the original evidence", instruction: "Make sure the initial bot or speech failure remains visible in Calls and logs even when the caller reaches a fallback." },
        { title: "Force a controlled failure", instruction: "Test safely, confirm the failover activates, and verify the caller experience plus both original and fallback evidence." },
      ],
      success: ["The chosen failure activates failover", "The caller reaches a safe outcome", "The original cause remains visible in evidence"],
      troubleshooting: [{ problem: "Failover never activates", fix: "Confirm the failure matches the configured condition and that the call uses the bot connection where the failover action is enabled." }],
      commonMistake: "Treating failover success as proof that the primary service is healthy.",
      docUrl: TECH_DOCS.botFeatures,
    },
  ],

  "platform-api": [
    {
      id: "api-create-identity",
      title: "Create a least-privilege API identity",
      objective: "Give one integration the minimum Live Hub access it needs.",
      duration: "6 min",
      path: ["Current account", "Access control (IAM)", "API clients"],
      architecture: ["Integration", "API client", "User group", "Live Hub API"],
      before: ["The integration's exact job", "Required read or write actions", "An approved secret store"],
      actions: [
        { title: "Name the client", instruction: "Create an API client named for the integration and environment, not for a person." },
        { title: "Copy the secret once", instruction: "Store the client ID and secret immediately in an approved secret store. Do not place them in code, screenshots, or support tickets." },
        { title: "Assign a group", instruction: "Add the client to the smallest user group that grants the required operation." },
        { title: "Lock unused identities", instruction: "Lock or delete old API clients instead of leaving replacement credentials active." },
      ],
      success: ["The client identifies one integration and environment", "Its secret is stored safely", "Its group grants only the needed access"],
      troubleshooting: [{ problem: "The API returns 403", fix: "Authentication may work while authorization fails. Check the client's user group and target operation before rotating the secret." }],
      docUrl: TECH_DOCS.apiClients,
    },
    {
      id: "api-get-token",
      title: "Authenticate to the management API",
      objective: "Obtain and use an OAuth bearer token for the standard Live Hub REST API.",
      duration: "6 min",
      path: ["REST API", "Authentication"],
      architecture: ["Client credentials", "Token endpoint", "Bearer token", "/api/v1 resource"],
      before: ["API client ID and secret", "The target resource", "A safe command-line or API testing environment"],
      actions: [
        { title: "Request the token", instruction: "Use the OAuth 2.0 client credentials grant with the API client ID and secret." },
        { title: "Keep it out of URLs", instruction: "Send the returned access token in the Authorization: Bearer header, never in a query string." },
        { title: "Call the base URL", instruction: "Use https://livehub.audiocodes.io with the /api/v1/ path for the standard management and monitoring resources." },
        { title: "Expect expiry", instruction: "Request a new token when it expires. Do not treat token refresh as a configuration failure." },
      ],
      success: ["A token is returned", "A protected API request succeeds", "No secret or token appears in a URL or saved evidence"],
      troubleshooting: [{ problem: "The token request returns 401", fix: "Verify the client ID, current client secret, account, and client state. Do not use the dialout Basic-auth pattern here." }],
      commonMistake: "Confusing standard REST API bearer authentication with the Dialout API's HTTP Basic authentication.",
      docUrl: TECH_DOCS.restAuthentication,
    },
    {
      id: "api-prove-calls",
      title: "Retrieve one call and prove automation works",
      objective: "Use a small read-only request to validate authentication, access, filtering, and response handling.",
      duration: "8 min",
      path: ["GET /api/v1/calls"],
      architecture: ["GET calls", "Filter", "Call record", "Call ID", "Automation proof"],
      before: ["A valid bearer token", "One recent test-call timestamp or number", "Call-data read permission"],
      actions: [
        { title: "Request a small collection", instruction: "Call GET /api/v1/calls with conservative pagination instead of retrieving the full history." },
        { title: "Filter the test", instruction: "Use the documented filtering, pagination, sorting, or free-text conventions to locate the known call." },
        { title: "Read one record", instruction: "Capture its identifiers, calling and called entities, timing, outcome, and performance fields." },
        { title: "Handle empty and denied states", instruction: "Distinguish no matching data from 401 authentication, 403 authorization, rate limits, and server errors." },
      ],
      success: ["The known call is returned", "Pagination and filtering are bounded", "The integration handles empty and error responses distinctly"],
      troubleshooting: [{ problem: "The portal shows the call but the API does not", fix: "Check account, token permissions, filter syntax, time zone, pagination, and whether personal-data visibility affects the fields you expect." }],
      docUrl: TECH_DOCS.restApi,
    },
  ],

  "account-admin": [
    {
      id: "account-choose-model",
      title: "Choose the right account structure",
      objective: "Use standalone, parent, and subaccount models intentionally before production objects multiply.",
      duration: "6 min",
      path: ["Current account", "Create account or Subaccounts"],
      architecture: ["Organization", "Parent or standalone", "Subaccounts", "Services and billing"],
      before: ["Who owns the service", "Whether you operate for customers", "Who pays", "Who needs isolation"],
      actions: [
        { title: "Choose standalone", instruction: "Use a standalone account when one organization operates and pays for its own Live Hub environment." },
        { title: "Choose parent and subaccounts", instruction: "Use a parent account when a provider or central team manages separate customer or business accounts beneath it." },
        { title: "Define ownership", instruction: "For every account, record who administers configuration, who pays, and who may view call content." },
        { title: "Switch deliberately", instruction: "After switching accounts, recheck the Current account banner before creating or editing anything." },
      ],
      success: ["The account type matches the operating model", "Administration and billing owners are known", "Isolation boundaries are documented"],
      troubleshooting: [{ problem: "A resource appears missing", fix: "Check Current account first. Resources belong to the account in which they were created." }],
      commonMistake: "Creating additional accounts to organize objects before deciding whether isolation, billing, or delegated administration is actually required.",
      docUrl: TECH_DOCS.accounts,
    },
    {
      id: "account-plan-billing",
      title: "Keep the account active and billable",
      objective: "Understand plan state, balance, outbound enablement, and billing ownership before calls reach production.",
      duration: "7 min",
      path: ["Billing", "Settings", "Account details"],
      architecture: ["Plan", "Balance or usage", "Active account", "Working calls"],
      before: ["Current plan and billing model", "Billing owner", "Expected call volume", "Required outbound capabilities"],
      actions: [
        { title: "Identify Trial or Essential", instruction: "A first account starts on Trial. Adding enough credit for a positive balance upgrades it to Essential, but does not by itself enable outbound PSTN through AudioCodes-supplied numbers." },
        { title: "Read prepaid or postpaid", instruction: "Prepaid accounts show Account Balance; postpaid accounts show Monthly Usage. Open Billing for the detailed report." },
        { title: "Protect continuity", instruction: "An account becomes inactive at zero or negative balance. Configure auto-recharge or the appropriate billing process before production traffic." },
        { title: "Review reports", instruction: "Use monthly reports and CSV export to reconcile usage by service without hard-coding prices into the Academy." },
      ],
      success: ["The plan and billing model are known", "A billing owner is assigned", "The account has a process that prevents accidental inactivity"],
      troubleshooting: [{ problem: "Many unrelated services stop together", fix: "Check account state and balance before diagnosing bots, SIP, or routing individually." }],
      commonMistake: "Treating a broad service failure as a technical outage before checking whether the account is inactive.",
      docUrl: TECH_DOCS.billing,
    },
    {
      id: "account-access-privacy",
      title: "Protect access and call data",
      objective: "Apply least privilege, retention, and support-sharing choices before real customer conversations arrive.",
      duration: "8 min",
      path: ["Access control (IAM)", "Settings", "Advanced"],
      architecture: ["User or API client", "Group and policy", "Call data", "Retention and sharing"],
      before: ["Named users and systems", "Required roles", "Recording and transcript policy", "Support-sharing approval"],
      actions: [
        { title: "Assign groups intentionally", instruction: "Place users and API clients in the smallest predefined or custom groups that grant their actual work." },
        { title: "Require strong sign-in", instruction: "Use MFA and your approved identity method. Separate human users from system API clients." },
        { title: "Set data visibility and retention", instruction: "Configure personal-data visibility plus recording and transcript retention according to policy and investigation needs." },
        { title: "Share only during support work", instruction: "Transcript sharing is per bot connection; AI agent log sharing is account-wide. Recordings must be sent manually." },
      ],
      success: ["Every identity has an intentional access group", "Retention matches policy", "Support sharing is off unless an investigation requires it"],
      troubleshooting: [{ problem: "A user cannot see a screen", fix: "Confirm account membership and group policy before adding a second user or granting administrator access." }],
      commonMistake: "Granting administrator access to solve a single missing permission.",
      docUrl: TECH_DOCS.userGroups,
    },
  ],
};
