const TECHDOCS_BASE = "https://techdocs.audiocodes.com/livehub";

/**
 * One maintained source for every official-documentation link in the Academy.
 * Keeping these URLs here prevents individual lessons from drifting to old
 * Help Center, staging, or placeholder pages.
 */
export const TECH_DOCS = {
  home: `${TECHDOCS_BASE}/`,
  signIn: `${TECHDOCS_BASE}/#LiveHub/signing-into-livehub.htm?TocPath=_____3`,
  userInterface: `${TECHDOCS_BASE}/#LiveHub/User-Interface.htm?TocPath=_____4`,
  accountPlans: `${TECHDOCS_BASE}/Content/LiveHub/User%20Account%20Plans.htm`,
  accountTypes: `${TECHDOCS_BASE}/Content/LiveHub/Accounts-types.htm`,
  accounts: `${TECHDOCS_BASE}/Content/LiveHub/Account%20and%20Sign%20Up.htm`,
  dashboard: `${TECHDOCS_BASE}/Content/LiveHub/Live%20Hub%20Dashboard.htm`,
  quickSetupWizard: `${TECHDOCS_BASE}/#LiveHub/Configuration%20Wizard.htm?TocPath=_____24`,
  aiAgent: `${TECHDOCS_BASE}/#AI-Agents/Add%20an%20AI%20Agent.htm?TocPath=AI%2520Agents%257CAgents%257C_____1`,
  aiAssistant: `${TECHDOCS_BASE}/#AI-Agents/AI%20Assistant.htm?TocPath=AI%2520Agents%257C_____24`,
  aiTools: `${TECHDOCS_BASE}/#AI-Agents/Tools.htm?TocPath=AI%2520Agents%257CTools%257C_____0`,
  agentAssistMode: `${TECHDOCS_BASE}/#AI-Agents/Agent%20assist%20mode.htm?TocPath=AI%2520Agents%257CAgent%2520assist%2520mode%257C_____0`,
  botFeatures: `${TECHDOCS_BASE}/Content/LiveHub/byoc_cloud_managing_features.htm`,
  botTest: `${TECHDOCS_BASE}/#LiveHub/Testing%20your%20Bot.htm?TocPath=Bot%2520connectivity%257C_____7`,
  voiceChannels: `${TECHDOCS_BASE}/Content/LiveHub/voice-channels.htm`,
  phoneNumbers: `${TECHDOCS_BASE}/Content/LiveHub/managing_numbers.htm`,
  phoneNumberPurchase: `${TECHDOCS_BASE}/Content/LiveHub/Purchasing%20Phone%20Numbers.htm`,
  supportedNumberCountries: `${TECHDOCS_BASE}/Content/LiveHub/Supported%20Country%20Telephone%20Numbers1.htm`,
  sipConnections: `${TECHDOCS_BASE}/Content/LiveHub/sip_connections.htm`,
  genericSip: `${TECHDOCS_BASE}/Content/LiveHub/adding-generic-sip-connection.htm`,
  teams: `${TECHDOCS_BASE}/Content/LiveHub/Creating%20Teams%20connection.htm`,
  teamsTenant: `${TECHDOCS_BASE}/Content/LiveHub/Configuring%20your%20tenant.htm`,
  teamsAssignNumbers: `${TECHDOCS_BASE}/#LiveHub/Assigning%20Phone%20Numbers.htm?TocPath=Voice%2520channels%257CMicrosoft%2520Teams%2520voice%2520integration%257CManaging%2520Teams%2520tenant%257C_____1`,
  teamsRouting: `${TECHDOCS_BASE}/Content/LiveHub/Creating%20%20routing%20rules.htm`,
  teamsTest: `${TECHDOCS_BASE}/#LiveHub/Testing%20your%20Teams%20connectivity.htm?TocPath=Voice%2520channels%257CMicrosoft%2520Teams%2520voice%2520integration%257C_____8`,
  whatsapp: `${TECHDOCS_BASE}/Content/LiveHub/buy-whats-app-number.htm`,
  clickToCall: `${TECHDOCS_BASE}/Content/LiveHub/Configuring-webrtc-click-to-call.htm`,
  routingOverview: `${TECHDOCS_BASE}/Content/LiveHub/Managing%20Routing.htm`,
  routing: `${TECHDOCS_BASE}/Content/LiveHub/Defining%20Routing.htm`,
  agentAssist: `${TECHDOCS_BASE}/Content/LiveHub/Agent%20assist.htm`,
  translation: `${TECHDOCS_BASE}/Content/LiveHub/Voice-translation.htm`,
  translationCreate: `${TECHDOCS_BASE}/Content/LiveHub/Create-Voice-translation.htm`,
  translationAutomatic: `${TECHDOCS_BASE}/Content/LiveHub/Configure-automatic-translation.htm`,
  translationDynamic: `${TECHDOCS_BASE}/Content/LiveHub/Configure-dynamic-translation.htm`,
  outboundCalling: `${TECHDOCS_BASE}/Content/LiveHub/byoc_Outbound%20Call.htm`,
  outboundAutomation: `${TECHDOCS_BASE}/Content/LiveHub/Campaign-Dialer.htm`,
  callHistory: `${TECHDOCS_BASE}/#LiveHub/Calls.htm?TocPath=Calls%257C_____0`,
  callTranscript: `${TECHDOCS_BASE}/#LiveHub/byoc_Call%20Transcript.htm?TocPath=Bot%2520connectivity%257CManage%2520%2520features%257C_____1`,
  callRecording: `${TECHDOCS_BASE}/#LiveHub/Call-Recording-workflow.htm?TocPath=_____22`,
  callTransfer: `${TECHDOCS_BASE}/#LiveHub/byoc_Call%20Transfer.htm?TocPath=Bot%2520connectivity%257CManage%2520%2520features%257C_____5`,
  statistics: `${TECHDOCS_BASE}/#LiveHub/Statistics.htm?TocPath=_____18`,
  alarms: `${TECHDOCS_BASE}/#LiveHub/Vewing%20Alarms.htm?TocPath=Alarm%2520%2526%2520alerts%2520management%257C_____0`,
  alarmThresholds: `${TECHDOCS_BASE}/#LiveHub/Define-alarm-thresholds.htm?TocPath=Alarm%2520%2526%2520alerts%2520management%257C_____3`,
  alarmNotifications: `${TECHDOCS_BASE}/Content/LiveHub/Configure-alarm-notification.htm`,
  billing: `${TECHDOCS_BASE}/Content/LiveHub/billing.htm`,
  userGroups: `${TECHDOCS_BASE}/#LiveHub/users-introduction.htm?TocPath=User%2520access%2520%2526%2520permissions%257C_____1`,
  apiClients: `${TECHDOCS_BASE}/#VAIC/api-introduction.htm?TocPath=User%2520access%2520%2526%2520permissions%257CAPI%2520Clients%257C_____0`,
  restApi: `${TECHDOCS_BASE}/#LiveHub/API/REST-API-VoiceAI-Connect-Cloud.htm?TocPath=REST%2520API%257C_____0`,
  restAuthentication: `${TECHDOCS_BASE}/#LiveHub/API/api-security.htm?TocPath=REST%2520API%257C_____2`,
  support: `${TECHDOCS_BASE}/#LiveHub/byoc_cloud_managing_help.htm?TocPath=Help%2520%2526%2520support%2520options%257C_____0`,
  releaseNotes: `${TECHDOCS_BASE}/#LiveHub/release-notes.htm?TocPath=_____28`,
} as const;
